# Generated by Django 4.0.4 on 2022-07-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.ImageField(default='', upload_to='template/', verbose_name='Изображение'),
        ),
    ]
