# Generated by Django 4.0.4 on 2022-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardex', '0002_template_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
